# Generated by Django 2.1.2 on 2018-11-23 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lead_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadgerated',
            name='published',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
